name: C/C++ CI

on:
   push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v4
    - name: CPU Information
      run:  lscpu || echo "CPU information not available"
    - name: Compiler Information
      run:  cc -v
    - name: Install dependencies
      run:  sudo apt update && sudo apt install libboost-dev libglib2.0-dev
    - name: make
      run: make
    - name: make bench
      working-directory: ./bench
      run: make BOOST=/usr/include && make report
 
